import { useState } from "react";
import { CopyButton, Field, ToolCard, inputClass, uid, usePersistentState } from "~/components/tools/shared/ToolUi";
type Card = { id: string; text: string; source: string; themeId: string | null };
type Theme = { id: string; name: string; insight: string };
type Saved = { schemaVersion: 1; sources: string[]; themes: Theme[]; cards: Card[] };
const initial: Saved = { schemaVersion: 1, sources: ["Interview notes"], themes: [{ id: "unsorted", name: "Unsorted", insight: "" }], cards: [] };
export default function AffinityBoard() {
  const [saved, setSaved] = usePersistentState<Saved>("tool:affinity-board", initial);
  const [raw, setRaw] = useState("");
  const [source, setSource] = useState("Interview notes");
  const [selected, setSelected] = useState<string | null>(null);
  const themes = saved.themes;
  const grouped = (themeId: string | null) => saved.cards.filter((card) => card.themeId === themeId);
  const split = () => { const cards = raw.split(/\n\s*\n|\n(?=\s*[-*]\s)/).map((text) => text.replace(/^\s*[-*]\s*/, "").trim()).filter(Boolean).map((text) => ({ id: uid("card"), text, source: source || "Untitled source", themeId: null })); if (cards.length) setSaved((current) => ({ ...current, cards: [...current.cards, ...cards], sources: current.sources.includes(source) ? current.sources : [...current.sources, source] })); setRaw(""); };
  const move = (cardId: string, themeId: string) => setSaved((current) => ({ ...current, cards: current.cards.map((card) => card.id === cardId ? { ...card, themeId: themeId === "unsorted" ? null : themeId } : card) }));
  const addTheme = () => setSaved((current) => ({ ...current, themes: [...current.themes, { id: uid("theme"), name: "New theme", insight: "" }] }));
  const markdown = `# Affinity map\n\n${themes.filter((theme) => theme.id !== "unsorted").map((theme) => `## ${theme.name}\n\n${theme.insight ? `> ${theme.insight}\n\n` : ""}${grouped(theme.id).map((card) => `- ${card.text} _(source: ${card.source})_`).join("\n")}`).join("\n\n")}`;
  const themeCount = themes.filter((theme) => theme.id !== "unsorted").map((theme) => ({ ...theme, count: grouped(theme.id).length })).sort((a, b) => b.count - a.count);
  return <div className="grid gap-6"><ToolCard title="Paste notes and split into cards"><div className="grid gap-3 md:grid-cols-[1fr_16rem]"><Field label="Source tag"><input className={inputClass} value={source} onChange={(e) => setSource(e.target.value)} /></Field><span className="hidden md:block" /><Field label="Notes"><textarea className={`${inputClass} min-h-28 md:col-span-2`} value={raw} onChange={(e) => setRaw(e.target.value)} placeholder="One snippet per blank line…" /></Field></div><button type="button" className="btn btn-primary btn-sm mt-3" onClick={split}>Split into cards</button></ToolCard><ToolCard title="Themes"><div className="flex flex-wrap gap-2">{themeCount.map((theme) => <span key={theme.id} className="rounded-full border border-ink-200 px-3 py-1 text-caption text-muted">{theme.name} · {theme.count}</span>)}</div><button type="button" className="btn btn-secondary btn-sm mt-4" onClick={addTheme}>Add theme</button></ToolCard><div className="grid gap-4 lg:grid-cols-3">{themes.map((theme) => <section key={theme.id} className="rounded-xl border border-ink-200 bg-surface-base p-4"><div className="flex items-center justify-between gap-2"><input className="min-w-0 border-0 bg-transparent text-h5 font-semibold text-strong focus:outline-none" value={theme.name} onChange={(e) => setSaved((current) => ({ ...current, themes: current.themes.map((candidate) => candidate.id === theme.id ? { ...candidate, name: e.target.value } : candidate) }))} /><span className="text-caption text-muted">{grouped(theme.id === "unsorted" ? null : theme.id).length}</span></div>{theme.id !== "unsorted" && <input className={`${inputClass} mt-3 text-caption`} placeholder="Insight one-liner" value={theme.insight} onChange={(e) => setSaved((current) => ({ ...current, themes: current.themes.map((candidate) => candidate.id === theme.id ? { ...candidate, insight: e.target.value } : candidate) }))} />}<div className="mt-3 grid gap-2">{grouped(theme.id === "unsorted" ? null : theme.id).map((card) => <button key={card.id} type="button" onClick={() => setSelected(selected === card.id ? null : card.id)} className={`rounded-lg border p-3 text-left ${selected === card.id ? "border-accent-600 bg-accent-50" : "border-ink-200"}`}><span className="block text-caption text-strong">{card.text}</span><span className="mt-1 block text-[11px] text-faint">{card.source}</span>{selected === card.id && <select className={`${inputClass} mt-2`} value={card.themeId ?? "unsorted"} onChange={(e) => move(card.id, e.target.value)}><option value="unsorted">Unsorted</option>{themes.filter((candidate) => candidate.id !== "unsorted").map((candidate) => <option key={candidate.id} value={candidate.id}>Move to {candidate.name}</option>)}</select>}</button>)}</div></section>)}</div><div className="flex items-center gap-3"><CopyButton value={markdown} /><span className="text-caption text-muted">Select a card to move it between columns.</span></div></div>;
}
