import { useMemo } from "react";
import { CopyButton, Field, ToolCard, inputClass, selectClass, uid, usePersistentState } from "~/components/tools/shared/ToolUi";

type Kind = "model" | "branch" | "context" | "cost" | "tokens" | "cwd" | "time" | "custom";
type Segment = { id: string; kind: Kind; color: string; label?: string; row?: number; enabled: boolean };
type Saved = { schemaVersion: 1; layout: "one" | "three"; segments: Segment[]; sample: { ctxPct: number; costUsd: number; branch: string; model: string; tokens: string; cwd: string; custom: string } };
const palette = ["var(--accent-700)", "var(--accent-500)", "var(--positive-600)", "var(--warning-600)", "var(--danger-600)", "var(--ink-100)", "var(--ink-400)", "var(--text-on-inverse)"];
const kinds: { kind: Kind; label: string }[] = [{ kind: "model", label: "Model name" }, { kind: "branch", label: "Git branch" }, { kind: "context", label: "Context left %" }, { kind: "cost", label: "Session cost" }, { kind: "tokens", label: "Tokens" }, { kind: "cwd", label: "Working directory" }, { kind: "time", label: "Time" }, { kind: "custom", label: "Custom text" }];
const initialSegments = (): Segment[] => kinds.map((item, index) => ({ id: uid("segment"), kind: item.kind, color: palette[index % palette.length], row: index % 3, enabled: index < 5 }));
const initial: Saved = { schemaVersion: 1, layout: "one", segments: initialSegments(), sample: { ctxPct: 72, costUsd: 0.42, branch: "codex/blog-tools", model: "claude-sonnet-5", tokens: "42k", cwd: "~/workspaces/site", custom: "ready" } };
const labelFor = (kind: Kind) => kinds.find((item) => item.kind === kind)?.label ?? kind;
const sampleValue = (kind: Kind, sample: Saved["sample"]) => ({ model: sample.model, branch: `⎇ ${sample.branch}`, context: `ctx ${sample.ctxPct}%`, cost: `$${sample.costUsd.toFixed(2)}`, tokens: sample.tokens, cwd: sample.cwd, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }), custom: sample.custom }[kind]);

function commandScript(saved: Saved) {
  const segmentLines = saved.segments.filter((segment) => segment.enabled).map((segment) => {
    const value = { model: '"$(jq -r \'.model.display_name // \"model\"\')"', branch: '"$(jq -r \'.workspace.current_dir // \"cwd\"\' | xargs basename)"', context: '"ctx $(jq -r \'.context_window.remaining_percentage // 0\')%"', cost: '"$$(jq -r \'.cost.total_cost_usd // 0 | tonumber | . * 100 | round / 100\')"', tokens: '"$(jq -r \'.context_window.total_input_tokens // 0\') in"', cwd: '"$(jq -r \'.workspace.current_dir // \"cwd\"\')"', time: '"$(date +%H:%M)"', custom: '"ready"' }[segment.kind];
    return `printf '%s' ${value} >> "$line"; printf '%s' '  ' >> "$line";`;
  }).join("\n");
  return `#!/usr/bin/env bash\nset -euo pipefail\nline=\"\"\n${segmentLines}\nprintf '%s\\n' \"$line\"`;
}

export default function StatuslinePlayground() {
  const [saved, setSaved] = usePersistentState<Saved>("tool:statusline-playground", initial);
  const enabled = saved.segments.filter((segment) => segment.enabled);
  const script = useMemo(() => commandScript(saved), [saved]);
  const settings = JSON.stringify({ statusLine: { type: "command", command: "~/.claude/statusline.sh" } }, null, 2);
  const toggle = (id: string) => setSaved((current) => ({ ...current, segments: current.segments.map((segment) => segment.id === id ? { ...segment, enabled: !segment.enabled } : segment) }));
  const move = (id: string, direction: -1 | 1) => setSaved((current) => { const index = current.segments.findIndex((segment) => segment.id === id); const next = index + direction; if (index < 0 || next < 0 || next >= current.segments.length) return current; const segments = [...current.segments]; [segments[index], segments[next]] = [segments[next], segments[index]]; return { ...current, segments }; });
  const markdown = `# Statusline\n\n${enabled.map((segment) => `- ${labelFor(segment.kind)} (${segment.color})`).join("\n")}`;

  return <div className="grid gap-6">
    <ToolCard title="Live preview"><div className="overflow-x-auto rounded-lg bg-surface-inverse p-4 font-mono text-caption text-on-inverse"><div className="flex min-w-max flex-wrap items-center gap-2">{enabled.filter((segment) => saved.layout === "one" || segment.row === 0).map((segment) => <span key={segment.id} style={{ color: segment.color }}>{sampleValue(segment.kind, saved.sample)}</span>)}</div>{saved.layout === "three" && [1, 2].map((row) => <div key={row} className="mt-2 flex min-w-max flex-wrap items-center gap-2">{enabled.filter((segment) => segment.row === row).map((segment) => <span key={segment.id} style={{ color: segment.color }}>{sampleValue(segment.kind, saved.sample)}</span>)}</div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button type="button" className={`btn btn-sm ${saved.layout === "one" ? "btn-primary" : "btn-secondary"}`} onClick={() => setSaved((current) => ({ ...current, layout: "one" }))}>One row</button><button type="button" className={`btn btn-sm ${saved.layout === "three" ? "btn-primary" : "btn-secondary"}`} onClick={() => setSaved((current) => ({ ...current, layout: "three" }))}>Three rows</button></div></ToolCard>
    <ToolCard title="Sample data"><div className="grid gap-4 md:grid-cols-3"><Field label="Context left %"><input className={inputClass} type="range" min="0" max="100" value={saved.sample.ctxPct} onChange={(e) => setSaved((current) => ({ ...current, sample: { ...current.sample, ctxPct: Number(e.target.value) } }))} /><span className="text-caption text-muted">{saved.sample.ctxPct}%</span></Field><Field label="Session cost"><input className={inputClass} type="number" step="0.01" value={saved.sample.costUsd} onChange={(e) => setSaved((current) => ({ ...current, sample: { ...current.sample, costUsd: Number(e.target.value) || 0 } }))} /></Field><Field label="Branch"><input className={inputClass} value={saved.sample.branch} onChange={(e) => setSaved((current) => ({ ...current, sample: { ...current.sample, branch: e.target.value } }))} /></Field><Field label="Model"><input className={inputClass} value={saved.sample.model} onChange={(e) => setSaved((current) => ({ ...current, sample: { ...current.sample, model: e.target.value } }))} /></Field><Field label="Custom text"><input className={inputClass} value={saved.sample.custom} onChange={(e) => setSaved((current) => ({ ...current, sample: { ...current.sample, custom: e.target.value } }))} /></Field></div></ToolCard>
    <ToolCard title="Segment palette"><div className="grid gap-3">{saved.segments.map((segment, index) => <div key={segment.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-ink-200 p-3"><button type="button" className={`btn btn-sm ${segment.enabled ? "btn-primary" : "btn-ghost"}`} onClick={() => toggle(segment.id)}>{segment.enabled ? "On" : "Off"}</button><strong className="min-w-32 text-caption text-strong">{labelFor(segment.kind)}</strong><select aria-label={`${labelFor(segment.kind)} color`} className={selectClass} value={segment.color} onChange={(e) => setSaved((current) => ({ ...current, segments: current.segments.map((item) => item.id === segment.id ? { ...item, color: e.target.value } : item) }))}>{palette.map((color) => <option key={color} value={color}>{color.replace("var(", "").replace(")", "")}</option>)}</select>{saved.layout === "three" && <select aria-label={`${labelFor(segment.kind)} row`} className="w-24 rounded-md border border-ink-200 bg-surface-base px-2 py-2 text-caption text-strong" value={segment.row ?? 0} onChange={(e) => setSaved((current) => ({ ...current, segments: current.segments.map((item) => item.id === segment.id ? { ...item, row: Number(e.target.value) } : item) }))}><option value="0">Row 1</option><option value="1">Row 2</option><option value="2">Row 3</option></select>}<button type="button" className="btn btn-ghost btn-sm" disabled={index === 0} onClick={() => move(segment.id, -1)}>↑</button><button type="button" className="btn btn-ghost btn-sm" disabled={index === saved.segments.length - 1} onClick={() => move(segment.id, 1)}>↓</button></div>)}</div></ToolCard>
    <ToolCard title="Export"><div className="flex flex-wrap gap-2"><CopyButton value={script} label="Copy bash script" /><CopyButton value={settings} label="Copy settings.json" /><CopyButton value={markdown} label="Copy summary" /></div><p className="mt-3 text-caption text-muted">The generated script reads Claude Code's JSON stdin fields: model.display_name, workspace.current_dir, context_window, and cost.total_cost_usd.</p><pre className="mt-4 max-h-80 overflow-auto rounded-lg bg-surface-inverse p-4 text-caption text-on-inverse">{script}</pre></ToolCard>
  </div>;
}
