import { useMemo } from "react";
import { CopyButton, Field, ToolCard, inputClass, selectClass, usePersistentState } from "~/components/tools/shared/ToolUi";
type Owner = "PO absorbs" | "Delegate" | "Shared";
type Row = { id: string; name: string; ba?: boolean; ux?: boolean; large?: boolean };
type Saved = { schemaVersion: 1; inputs: { engineers: number; hasBA: boolean; hasPM: boolean; hasUXR: boolean; teams: number }; overrides: Record<string, Owner> };
const rows: Row[] = [{ id: "discovery", name: "Discovery interviews" }, { id: "backlog", name: "Backlog ordering" }, { id: "acceptance", name: "Acceptance review" }, { id: "stakeholders", name: "Stakeholder updates", large: true }, { id: "okrs", name: "OKR drafting", large: true }, { id: "sprint", name: "Sprint planning" }, { id: "spec", name: "Spec writing", large: true }, { id: "analytics", name: "Analytics review", ba: true }, { id: "support", name: "Support triage", large: true }, { id: "roadmap", name: "Roadmap comms", large: true }, { id: "pricing", name: "Pricing input", ba: true }, { id: "release", name: "Release notes", large: true }, { id: "demo", name: "Demo hosting" }, { id: "experiments", name: "Experiment design", ux: true }, { id: "slicing", name: "User-story slicing", large: true }, { id: "dependencies", name: "Dependency wrangling", large: true }, { id: "hiring", name: "Hiring input", large: true }, { id: "research", name: "Marketing research", ba: true }];
const initial: Saved = { schemaVersion: 1, inputs: { engineers: 6, hasBA: false, hasPM: false, hasUXR: false, teams: 1 }, overrides: {} };
function defaultOwner(row: Row, inputs: Saved["inputs"]): Owner { if (row.ba && inputs.hasBA) return "Delegate"; if (row.ux && inputs.hasUXR) return "Shared"; if (row.id === "backlog" || row.id === "acceptance") return "PO absorbs"; if (row.large && inputs.engineers > 8) return "Delegate"; if (inputs.teams > 1 && ["stakeholders", "roadmap", "dependencies"].includes(row.id)) return "Shared"; if (inputs.hasPM && ["okrs", "pricing", "roadmap"].includes(row.id)) return "Shared"; return "PO absorbs"; }
export default function PoResponsibilityMap() {
  const [saved, setSaved] = usePersistentState<Saved>("tool:po-responsibility-map", initial);
  const owners = useMemo(() => Object.fromEntries(rows.map((row) => [row.id, saved.overrides[row.id] ?? defaultOwner(row, saved.inputs)])) as Record<string, Owner>, [saved]);
  const counts = (Object.values(owners).reduce((result, owner) => ({ ...result, [owner]: (result[owner] ?? 0) + 1 }), {} as Record<string, number>));
  const markdown = `| Responsibility | Owner |\n| --- | --- |\n${rows.map((row) => `| ${row.name} | ${owners[row.id]} |`).join("\n")}`;
  return <div className="grid gap-6"><ToolCard title="Team shape"><div className="grid gap-4 md:grid-cols-5"><Field label={`${saved.inputs.engineers} engineers`}><input type="range" min="2" max="30" value={saved.inputs.engineers} onChange={(e) => setSaved((current) => ({ ...current, inputs: { ...current.inputs, engineers: Number(e.target.value) } }))} /></Field>{[["hasBA", "Dedicated BA"], ["hasPM", "PM above PO"], ["hasUXR", "UX researcher"]].map(([key, label]) => <label key={key} className="flex items-center gap-2 text-caption text-muted"><input type="checkbox" checked={saved.inputs[key as "hasBA" | "hasPM" | "hasUXR"]} onChange={(e) => setSaved((current) => ({ ...current, inputs: { ...current.inputs, [key]: e.target.checked } }))} />{label}</label>)}<Field label="Teams"><input className={inputClass} type="number" min="1" max="8" value={saved.inputs.teams} onChange={(e) => setSaved((current) => ({ ...current, inputs: { ...current.inputs, teams: Number(e.target.value) || 1 } }))} /></Field></div></ToolCard><div className="grid gap-4 md:grid-cols-4"><ToolCard title="PO absorbs"><p className="text-display-md text-strong">{counts["PO absorbs"] ?? 0}</p></ToolCard><ToolCard title="Delegated"><p className="text-display-md text-strong">{counts.Delegate ?? 0}</p></ToolCard><ToolCard title="Shared"><p className="text-display-md text-strong">{counts.Shared ?? 0}</p></ToolCard><ToolCard title="Capacity"><p className={`text-body font-semibold ${(counts["PO absorbs"] ?? 0) > 8 ? "text-danger-700" : "text-positive-700"}`}>{(counts["PO absorbs"] ?? 0) > 8 ? "Spread is too thin" : "Looks manageable"}</p></ToolCard></div><ToolCard title="Responsibility map"><div className="grid gap-2">{rows.map((row) => <div key={row.id} className="grid gap-2 rounded-lg border border-ink-200 p-3 md:grid-cols-[1fr_12rem_auto]"><span className="text-body text-strong">{row.name}</span><select className={selectClass} value={owners[row.id]} onChange={(e) => setSaved((current) => ({ ...current, overrides: { ...current.overrides, [row.id]: e.target.value as Owner } }))}><option>PO absorbs</option><option>Delegate</option><option>Shared</option></select>{saved.overrides[row.id] && <span className="text-caption text-accent-700">edited</span>}</div>)}</div><div className="mt-4"><CopyButton value={markdown} /></div></ToolCard></div>;
}
