import { useMemo } from "react";
import { CopyButton, Field, ToolCard, inputClass, selectClass, uid, usePersistentState } from "~/components/tools/shared/ToolUi";

type Item = { id: string; name: string; reach: number; impact: number; confidence: number; effort: number; ease: number };
type Saved = { schemaVersion: 1; framework: "rice" | "ice"; items: Item[]; sliders: { confidenceHaircut: number; effortInflation: number } };
const impacts = [0.25, 0.5, 1, 2, 3];
const blank = (name = "New idea"): Item => ({ id: uid("item"), name, reach: 100, impact: 1, confidence: 80, effort: 2, ease: 2 });
const score = (item: Item, saved: Saved) => saved.framework === "rice" ? (item.reach * item.impact * (item.confidence / 100) * saved.sliders.confidenceHaircut) / Math.max(0.1, item.effort * saved.sliders.effortInflation) : item.impact * (item.confidence / 100) * saved.sliders.confidenceHaircut * item.ease;

export default function RiceScorer() {
  const [saved, setSaved] = usePersistentState<Saved>("tool:rice-scorer", { schemaVersion: 1, framework: "rice", items: [blank("Improve onboarding"), blank("Faster search"), blank("Team invites")], sliders: { confidenceHaircut: 1, effortInflation: 1 } });
  const ranked = useMemo(() => [...saved.items].map((item) => ({ item, score: score(item, saved) })).sort((a, b) => b.score - a.score), [saved]);
  const oldRank = useMemo(() => [...saved.items].sort((a, b) => score(b, { ...saved, sliders: { confidenceHaircut: 1, effortInflation: 1 } }) - score(a, { ...saved, sliders: { confidenceHaircut: 1, effortInflation: 1 } })).map((item) => item.id), [saved]);
  const patchItem = (id: string, patch: Partial<Item>) => setSaved((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const markdown = `| Rank | Item | Score |\n| ---: | --- | ---: |\n${ranked.map(({ item, score: value }, index) => `| ${index + 1} | ${item.name} | ${value.toFixed(2)} |`).join("\n")}`;
  return <div className="grid gap-6">
    <ToolCard title="Framework and sensitivity"><div className="grid gap-4 md:grid-cols-3"><Field label="Framework"><select className={selectClass} value={saved.framework} onChange={(e) => setSaved((current) => ({ ...current, framework: e.target.value as "rice" | "ice" }))}><option value="rice">RICE · reach × impact × confidence ÷ effort</option><option value="ice">ICE · impact × confidence × ease</option></select></Field><Field label={`Confidence haircut · ${Math.round(saved.sliders.confidenceHaircut * 100)}%`}><input type="range" min="0.5" max="1" step="0.05" value={saved.sliders.confidenceHaircut} onChange={(e) => setSaved((current) => ({ ...current, sliders: { ...current.sliders, confidenceHaircut: Number(e.target.value) } }))} /></Field><Field label={`Effort inflation · ${saved.sliders.effortInflation.toFixed(1)}×`}><input type="range" min="1" max="2" step="0.1" value={saved.sliders.effortInflation} onChange={(e) => setSaved((current) => ({ ...current, sliders: { ...current.sliders, effortInflation: Number(e.target.value) } }))} /></Field></div></ToolCard>
    <ToolCard title="Score items"><div className="grid gap-3">{saved.items.map((item) => <div key={item.id} className="grid gap-3 rounded-lg border border-ink-200 p-3 md:grid-cols-6"><Field label="Name"><input className={inputClass} value={item.name} onChange={(e) => patchItem(item.id, { name: e.target.value })} /></Field>{saved.framework === "rice" && <Field label="Reach / qtr"><input className={inputClass} type="number" value={item.reach} onChange={(e) => patchItem(item.id, { reach: Number(e.target.value) || 0 })} /></Field>}<Field label="Impact"><select className={selectClass} value={item.impact} onChange={(e) => patchItem(item.id, { impact: Number(e.target.value) })}>{impacts.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="Confidence %"><select className={selectClass} value={item.confidence} onChange={(e) => patchItem(item.id, { confidence: Number(e.target.value) })}><option value="50">50</option><option value="80">80</option><option value="100">100</option></select></Field><Field label={saved.framework === "rice" ? "Effort weeks" : "Ease 1–5"}><input className={inputClass} type="number" min="0.1" max={saved.framework === "rice" ? undefined : 5} step="0.1" value={saved.framework === "rice" ? item.effort : item.ease} onChange={(e) => patchItem(item.id, saved.framework === "rice" ? { effort: Number(e.target.value) || 0.1 } : { ease: Number(e.target.value) || 0.1 })} /></Field><button type="button" className="self-end text-caption font-semibold text-danger-700 link-underline" onClick={() => setSaved((current) => ({ ...current, items: current.items.filter((candidate) => candidate.id !== item.id) }))}>Remove</button></div>)}</div><button type="button" className="btn btn-primary btn-sm mt-4" onClick={() => setSaved((current) => ({ ...current, items: [...current.items, blank()] }))}>Add item</button></ToolCard>
    <ToolCard title={`Ranked ${saved.framework.toUpperCase()} view`}><div className="grid gap-2">{ranked.map(({ item, score: value }, index) => { const before = oldRank.indexOf(item.id) + 1; const moved = before !== index + 1; return <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-ink-200 p-3"><span><strong className="text-body text-strong">{index + 1}. {item.name}</strong><span className="ml-2 text-caption text-muted">{value.toFixed(2)}</span></span>{moved && <span className="text-caption font-semibold text-accent-700">moved {before} → {index + 1}</span>}</div>})}</div><div className="mt-4"><CopyButton value={markdown} /></div></ToolCard>
  </div>;
}
