import { useMemo } from "react";
import { CopyButton, Field, ToolCard, inputClass, selectClass, uid, usePersistentState } from "~/components/tools/shared/ToolUi";

type Assumption = { id: string; text: string; type: "desirability" | "viability" | "feasibility" | "usability"; importance: number; evidence: number };
const types = ["desirability", "viability", "feasibility", "usability"] as const;
const colors: Record<Assumption["type"], string> = { desirability: "var(--accent-600)", viability: "var(--positive-600)", feasibility: "var(--warning-600)", usability: "var(--danger-600)" };
const blank = (): Assumption => ({ id: uid("assumption"), text: "New assumption", type: "desirability", importance: 3, evidence: 2 });
const quadrant = (item: Assumption) => item.importance >= 3 ? item.evidence >= 3 ? "Monitor" : "Test first" : item.evidence >= 3 ? "Ignore" : "Park";

export default function AssumptionMapper() {
  const [assumptions, setAssumptions] = usePersistentState<{ schemaVersion: 1; assumptions: Assumption[] }>("tool:assumption-mapper", { schemaVersion: 1, assumptions: [blank()] });
  const risky = useMemo(() => assumptions.assumptions.filter((item) => quadrant(item) === "Test first").sort((a, b) => b.importance - a.importance), [assumptions.assumptions]);
  const patch = (id: string, changes: Partial<Assumption>) => setAssumptions((current) => ({ ...current, assumptions: current.assumptions.map((item) => item.id === id ? { ...item, ...changes } : item) }));
  const markdown = `# Assumptions\n\n${assumptions.assumptions.map((item) => `- **${item.text}** (${item.type}; importance ${item.importance}/5, evidence ${item.evidence}/5)\n  - Quadrant: ${quadrant(item)}${quadrant(item) === "Test first" ? `\n  - Test: We believe ${item.text}. We will know we are wrong if…` : ""}`).join("\n")}`;
  return <div className="grid gap-6">
    <ToolCard title="Importance × evidence map"><div className="relative mx-auto aspect-square max-w-xl rounded-lg border border-ink-200 bg-surface-raised p-8"><div className="absolute inset-x-8 top-1/2 border-t border-dashed border-ink-300" /><div className="absolute inset-y-8 left-1/2 border-l border-dashed border-ink-300" /><span className="absolute left-3 top-3 text-caption font-semibold text-accent-700">Test first</span><span className="absolute right-3 top-3 text-caption font-semibold text-muted">Monitor</span><span className="absolute bottom-3 left-3 text-caption font-semibold text-muted">Park</span><span className="absolute bottom-3 right-3 text-caption font-semibold text-muted">Ignore</span>{assumptions.assumptions.map((item) => <span key={item.id} title={`${item.text} · ${quadrant(item)}`} className="absolute flex size-4 -translate-x-1/2 translate-y-1/2 items-center justify-center rounded-full border-2 border-surface-base" style={{ left: `${(item.evidence / 5) * 100}%`, bottom: `${(item.importance / 5) * 100}%`, background: colors[item.type] }} />)}</div><div className="mt-4 flex flex-wrap gap-3 text-caption text-muted">{types.map((type) => <span key={type}><i className="mr-1 inline-block size-2 rounded-full" style={{ background: colors[type] }} />{type}</span>)}</div></ToolCard>
    <ToolCard title="Assumption list"><div className="grid gap-3">{assumptions.assumptions.map((item) => <div key={item.id} className="grid gap-3 rounded-lg border border-ink-200 p-3 md:grid-cols-5"><Field label="Assumption"><input className={inputClass} value={item.text} onChange={(e) => patch(item.id, { text: e.target.value })} /></Field><Field label="Type"><select className={selectClass} value={item.type} onChange={(e) => patch(item.id, { type: e.target.value as Assumption["type"] })}>{types.map((type) => <option key={type}>{type}</option>)}</select></Field><Field label={`Importance ${item.importance}/5`}><input type="range" min="1" max="5" value={item.importance} onChange={(e) => patch(item.id, { importance: Number(e.target.value) })} /></Field><Field label={`Evidence ${item.evidence}/5`}><input type="range" min="1" max="5" value={item.evidence} onChange={(e) => patch(item.id, { evidence: Number(e.target.value) })} /></Field><button type="button" className="self-end text-caption font-semibold text-danger-700 link-underline" onClick={() => setAssumptions((current) => ({ ...current, assumptions: current.assumptions.filter((candidate) => candidate.id !== item.id) }))}>Remove</button></div>)}</div><button type="button" className="btn btn-primary btn-sm mt-4" onClick={() => setAssumptions((current) => ({ ...current, assumptions: [...current.assumptions, blank()] }))}>Add assumption</button></ToolCard>
    <ToolCard title={`Test first · ${risky.length}`}><div className="grid gap-3">{risky.length ? risky.map((item) => <div key={item.id} className="rounded-lg border border-accent-600/30 bg-accent-50 p-3"><strong className="text-body text-strong">{item.text}</strong><p className="mt-1 text-caption text-muted">We believe {item.text}. We will know we are wrong if…</p></div>) : <p className="text-caption text-muted">No high-importance, low-evidence assumptions yet.</p>}</div><div className="mt-4"><CopyButton value={markdown} /></div></ToolCard>
  </div>;
}
