import { useEffect, useMemo, useState } from "react";
import { CopyButton, Field, ToolCard, inputClass, selectClass, usePersistentState } from "~/components/tools/shared/ToolUi";
type Listen = { ts: number; artist: string; track: string; album: string };
type Range = "all" | "year" | "90d";
const CAP = 100000;
function csvRows(text: string): string[][] { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (char === '"' && text[i + 1] === '"' && quoted) { cell += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { row.push(cell); cell = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[i + 1] === "\n") i += 1; row.push(cell); if (row.some((value) => value.trim())) rows.push(row); row = []; cell = ""; } else cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } return rows; }
function normalizeJson(value: unknown): Listen[] { const array = Array.isArray(value) ? value : value && typeof value === "object" && Array.isArray((value as { listens?: unknown }).listens) ? (value as { listens: unknown[] }).listens : []; return array.map((entry) => { const item = (entry ?? {}) as Record<string, unknown>; const metadata = (item.track_metadata ?? item.trackMetadata ?? {}) as Record<string, unknown>; const ts = Number(item.listened_at ?? item.timestamp ?? item.ts); return { ts: ts < 2e10 ? ts * 1000 : ts, artist: String(metadata.artist_name ?? metadata.artist ?? item.artist ?? "Unknown artist"), track: String(metadata.track_name ?? metadata.track ?? item.track ?? "Unknown track"), album: String(metadata.release_name ?? metadata.album ?? item.album ?? "") }; }).filter((item) => Number.isFinite(item.ts) && item.artist !== "Unknown artist"); }
function normalizeCsv(text: string): Listen[] { const rows = csvRows(text); if (rows.length < 2) return []; const headers = rows[0].map((header) => header.trim().toLowerCase()); const find = (names: string[]) => names.map((name) => headers.indexOf(name)).find((index) => index >= 0) ?? -1; const artist = find(["artist", "artist_name", "artist name"]); const track = find(["track", "title", "track_name", "track name"]); const album = find(["album", "release", "release_name"]); const date = find(["date", "datetime", "timestamp", "listened_at", "played"]); if (artist < 0 || track < 0 || date < 0) return []; return rows.slice(1, CAP + 1).map((row) => ({ ts: Date.parse(row[date]), artist: row[artist]?.trim() ?? "", track: row[track]?.trim() ?? "", album: album >= 0 ? row[album]?.trim() ?? "" : "" })).filter((item) => Number.isFinite(item.ts) && item.artist && item.track); }
function Chart({ title, values }: { title: string; values: [string, number][] }) { const max = Math.max(...values.map(([, value]) => value), 1); return <div className="rounded-lg border border-ink-200 p-4"><h3 className="text-body font-semibold text-strong">{title}</h3><svg className="mt-3 h-48 w-full" viewBox="0 0 600 180" role="img" aria-label={title}>{values.map(([label, value], index) => { const width = Math.max(4, (value / max) * 500); const y = 12 + index * Math.min(24, 168 / Math.max(values.length, 1)); return <g key={label}><text x="0" y={y + 12} fontSize="11" fill="currentColor">{label.slice(0, 18)}</text><rect x="110" y={y} width={width} height="14" rx="4" fill="var(--accent-600)" /><text x={120 + width} y={y + 12} fontSize="11" fill="currentColor">{value}</text></g>; })}</svg></div>; }
export default function ScrobbleStats() {
  const [listens, setListens] = useState<Listen[]>([]); const [prefs, setPrefs] = usePersistentState<{ schemaVersion: 1; range: Range }>("tool:scrobble-stats-prefs", { schemaVersion: 1, range: "all" }); const [range, setRange] = useState<Range>(prefs.range); const [format, setFormat] = useState(""); const [error, setError] = useState(""); const [truncated, setTruncated] = useState(false);
  useEffect(() => setRange(prefs.range), [prefs.range]);
  const ingest = (text: string) => { try { const trimmed = text.trim(); const json = trimmed.startsWith("[") || trimmed.startsWith("{"); const parsed = json ? normalizeJson(JSON.parse(trimmed)) : normalizeCsv(trimmed); if (!parsed.length) throw new Error("No rows"); setListens(parsed.slice(0, CAP)); setTruncated(parsed.length > CAP); setFormat(json ? "ListenBrainz JSON" : "Scrobble CSV"); setError(""); } catch { setListens([]); setFormat(""); setError("Could not recognize that export. Use ListenBrainz JSON with listened_at and track_metadata, or CSV columns artist, track, and date."); } };
  const filtered = useMemo(() => { const now = Date.now(); const cutoff = range === "year" ? now - 365 * 864e5 : range === "90d" ? now - 90 * 864e5 : 0; return listens.filter((listen) => listen.ts >= cutoff); }, [listens, range]);
  const stats = useMemo(() => { const artists = new Map<string, number>(); const months = new Map<string, number>(); const hours = Array.from({ length: 24 }, (_, hour) => [`${hour}:00`, 0] as [string, number]); const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => [day, 0] as [string, number]); filtered.forEach((listen) => { const date = new Date(listen.ts); artists.set(listen.artist, (artists.get(listen.artist) ?? 0) + 1); const month = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; months.set(month, (months.get(month) ?? 0) + 1); hours[date.getHours()][1] += 1; weekdays[date.getDay()][1] += 1; }); const artistValues = [...artists.entries()].sort((a, b) => b[1] - a[1]).slice(0, 15); const busiest = weekdays.reduce((best, item) => item[1] > best[1] ? item : best, weekdays[0]); return { artistValues, monthValues: [...months.entries()].sort(), hours, weekdays, artists: artists.size, tracks: new Set(filtered.map((listen) => listen.track)).size, busiest: busiest[0] }; }, [filtered]);
  const markdown = `# Listening stats\n\n- Listens: ${filtered.length}\n- Unique artists: ${stats.artists}\n- Unique tracks: ${stats.tracks}\n- Busiest weekday: ${stats.busiest}\n\n## Top artists\n${stats.artistValues.map(([artist, count]) => `- ${artist}: ${count}`).join("\n")}`;
  const onFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => ingest(String(reader.result ?? "")); reader.readAsText(file); };
  return <div className="grid gap-6"><ToolCard title="Import listening history"><div className="flex flex-wrap items-center gap-3"><label className="btn btn-secondary btn-sm cursor-pointer">Drop / open file<input className="sr-only" type="file" accept=".csv,.json,text/csv,application/json" onChange={(e) => onFile(e.target.files?.[0])} /></label><span className="text-caption text-muted">Files stay in this browser; listen data is not saved to localStorage.</span></div><textarea className={`${inputClass} mt-4 min-h-36 font-mono text-caption`} placeholder="Paste Last.fm CSV or ListenBrainz JSON…" onChange={(e) => ingest(e.target.value)} />{error && <p className="mt-2 text-caption text-danger-700">{error}</p>}{format && <p className="mt-2 text-caption text-positive-700">Detected {format} · {listens.length.toLocaleString()} rows{truncated ? " (capped at 100,000)" : ""}</p>}</ToolCard>{listens.length > 0 && <><ToolCard title="Time range"><Field label="Show"><select className={`${selectClass} max-w-xs`} value={range} onChange={(e) => { const value = e.target.value as Range; setRange(value); setPrefs({ schemaVersion: 1, range: value }); }}><option value="all">All listens</option><option value="year">Last year</option><option value="90d">Last 90 days</option></select></Field></ToolCard><div className="grid gap-4 md:grid-cols-4"><ToolCard title="Listens"><p className="text-display-md text-strong">{filtered.length.toLocaleString()}</p></ToolCard><ToolCard title="Artists"><p className="text-display-md text-strong">{stats.artists}</p></ToolCard><ToolCard title="Tracks"><p className="text-display-md text-strong">{stats.tracks}</p></ToolCard><ToolCard title="Busiest day"><p className="text-display-md text-strong">{stats.busiest}</p></ToolCard></div><div className="grid gap-4 md:grid-cols-2"><Chart title="Top artists" values={stats.artistValues} /><Chart title="Listens per month" values={stats.monthValues} /><Chart title="By hour" values={stats.hours} /><Chart title="By weekday" values={stats.weekdays} /></div><div className="flex items-center gap-3"><CopyButton value={markdown} /><span className="text-caption text-muted">UI preference saved: {prefs.range}.</span></div></>}</div>;
}
